### ISSUE TITLE
Feature Request: Ability to view all images on a new tab

### ISSUE THREAD

**Issue by moisesbites** [belaviyo/save-images#10]
the extension would open a new tab where all images in the links detected will be showed.
The images would be resized to width of browser proportionaly, or by a configurable parameter of width.
So, after that, the tab would be saved in a folder, or not.

**Comment by belaviyo** [comment]
So basically the gallery view now has a button to be opened in a browser tab. Also, it is possible to open a single image by clicking on the "size" property. Images can now allocate 100% width. The height is not flexible. There is no good way to use the space properly. I'll investigate more.

**Comment by moisesbites** [comment]
Would be good to open directly by a menu item, in one step. Please, see the good example from this old extension https://addons.mozilla.org/pt-BR/firefox/addon/save-images/.

Thank you. :-)

**Comment by belaviyo** [comment]
You mean to have a menu item in the right-click context menu over page context for instance? If so it is pretty complex at this moment. This extension does not inject any script into web pages at all (to absolutely have no resource usage when it is not active). So collecting all images from the context menu requires a new injection and then collection. For instance, consider deep search feature that we have. It takes time to evaluate all images and links. 

I am not saying it is not possible but requires a lot of work!

**Comment by moisesbites** [comment]
Okay. I guess so. Anyway thank you.
