### ISSUE TITLE
Sorry this issue is about your another repo with no Issues tab: https://github.com/openstyles/native-client: the license question: Gentoo Guru removed my ebuild because the original project you forked - have no license

### ISSUE THREAD

**Issue by vitaly-zdanevich** [belaviyo/save-images#103]
Hi, I am about this removal https://github.com/gentoo/guru/commit/17ce9413138cbd22bdff4ddb26e205f735e3bbee#diff-de89c63c4a2f61950d8337a8c2be1939190e122bba9dd4cad2c5a53a7f2814afL9

Quote:
> Licensing issues: upstream slapped a license over a fork; they most
probably had no rights to do that.

And yes - you forked https://github.com/openstyles/native-client that have no license.  I am not sure what to do - I want to return it to Gentoo Guru... Any thoughts?

**Comment by belaviyo** [comment]
I have no idea what this openstyles/native-client does. Mine is a fork from 
https://github.com/andy-portmen/native-client

You need to point to the original project.

**Comment by vitaly-zdanevich** [comment]
but no
![image](https://github.com/user-attachments/assets/baec501d-be28-45aa-a85a-a54a9f020d9e)

**Comment by belaviyo** [comment]
I see! Maybe this one was smaller and I initially started from it. Anyhow the main project is `andy-portmen/native-client` so you should fork from it.
