### ISSUE TITLE
Feature Request: take file name from http headers, not from the link

### ISSUE THREAD

**Issue by lqp** [belaviyo/save-images#16]
There are images attached to a messages on a forums based on SMF (probably also other but i am does not checked).  When I am manually download them, "save file"  dialog offer correct name of file to be saved. 

But when I am use your extension to save all images from page, they saved as "index - 1.php","index - 2.php" etc. It is annoying. 

AFAIK (I did not dig deep) this is because browser get filename from the http response, not from the link text. 

Please either fix it or make option to get file name from http. 

example link
http://forum.woodtools.ru/index.php?topic=79437.0

My browser Firefox 62, my platform Linux 32bit (debian)

**Comment by belaviyo** [comment]
Thanks for the report. This should get fixed on the next release.
