### ISSUE TITLE
cannot collect images on this tab

### ISSUE THREAD

**Issue by Jan02** [belaviyo/save-images#2]
Cannot collect images on this tab
 
Missing host permission for the tab 
see:
https://framapic.org/LCzkNHjmSKFK/o9iKvwvsQ1JP

**Comment by belaviyo** [comment]
What was the URL of the tab that you wanted to collect images from?

**Comment by Jan02** [comment]
any page didn't work

**Comment by Jan02** [comment]
https://addons.mozilla.org/en-US/firefox/search/?page=6&sort=updated&type=extension

**Comment by belaviyo** [comment]
Web stores are restricted domains. For Firefox, addons.mozilla.org is the webstore and hence the extension cannot inject script into.

**Comment by kelvinwop** [comment]
I can't use it on locally stored html pages with images on a CDN

**Comment by khyveasna** [comment]
Joe

**Comment by auilab** [comment]
How about from google image search results?  I don't see how that is a security risk.  That may be there policy on the store, but not here.  So why not include that option?

**Comment by belaviyo** [comment]
@auilab is this on opera? If so go to the extensions manager and enable this extension on search pages.

**Comment by auilab** [comment]
> @auilab is this on opera? If so go to the extensions manager and enable this extension on search pages.

Solved!  You are amazing.

**Comment by Nurruddin** [comment]
> I can't use it on locally stored html pages with images on a CDN

I have the same issue
