### ISSUE TITLE
Feature Request : Better renaming.

### ISSUE THREAD

**Issue by Betsy25** [belaviyo/save-images#21]
Hi, could it be better to rename the files to their actual filename instead of image-* ?
Please take a look how to extension "Tab Image Saver" does it.

Otherwise, great extension!

**Comment by Betsy25** [comment]
Hi belaviyo,

[Here's](http://hayday.wikia.com/wiki/Goods_List) an example page, for instance trying to grab all .png images with these dimensions:

Min width: 100
Max width: 120
Min height: 100
Max height: 120

**Comment by belaviyo** [comment]
Thanks! will be fixed

**Comment by Betsy25** [comment]
Ah oops, seems you're (partly) right.
It seems to not remember the settings when you switch to another tab (that was already open when you set the options). You need to reload the tab again for the settings to kick in, otherwise it will not use your last used settings.

**Comment by belaviyo** [comment]
what is your browser version and os?

**Comment by Betsy25** [comment]
> 
> 
> what is your browser version and os?

I'm testing this on Firefox Nightly v65 on Win7x64.

**Comment by belaviyo** [comment]
If you have cookies disabled, check https://stackoverflow.com/questions/48006926/localstorage-access-from-firefox-extension-scope

**Comment by Betsy25** [comment]
Well, seems like things are only worse on Firefox stable.
It indeed doesn't seem to preserve the settings + it only finds a fraction of what it should find (25 instead of 254)...

**Comment by belaviyo** [comment]
Looks good then. Releasing 0.5.5

**Comment by Betsy25** [comment]
I don't know what you specifically did with the newest 0.5.5, but with the same settings on the same URL as posted above, it now only finds 83 instead of the 254 images ?????
Even in FF stable.
