### ISSUE TITLE
Feature Request: File renaming based on img HTML attributes

### ISSUE THREAD

**Issue by shane64** [belaviyo/save-images#23]
Hello,

  Would it be possible to permit more options (in square brackets) in the "File Mask" section of the UI to allow drawing on other attributes in the original "img" tag if they exist (like "alt", "class", "title") to construct the image filenames?  Perhaps to avoid hard-coding all possible attributes, the user could provide something like [att=title] or [att=alt] as part of the "File Mask" (and silently fail if that particular attribute doesn't exist)?

Thanks.

**Comment by dimeptr** [comment]
In the following patch I have added the possibility to use the alt attribute for renaming of files
[alt-keyword.diff.txt](https://github.com/belaviyo/save-images/files/4307128/alt-keyword.diff.txt)

**Comment by belaviyo** [comment]
Thanks @shane64  for the feature request and thanks @dimeptr for the implementation.
