### ISSUE TITLE
Download cancels due to addon's window closing from site's javascript

### ISSUE THREAD

**Issue by guitarjorge24** [belaviyo/save-images#28]
I tried using your addon on this site:
http://www.element3ds.com/forum.php?mod=viewthread&tid=146550

However, the addon's window closes after 3 seconds and the download gets canceled. I think this happens because the website has a gallery of rotating images that change every few seconds using javascript. When the images rotate, the addon window closes. I tried disabling the website's javascript but then this addon didn't run at all.

Maybe there could be an option to make the window permanent so it won't close even if javascript from the website is running in the background.

**Comment by belaviyo** [comment]
Thanks for the report. Should be fixed by the next release.
