### ISSUE TITLE
Feature Request: Preview of All Images

### ISSUE THREAD

**Issue by DelKatey** [belaviyo/save-images#3]
A preview of the images might be helpful to let users decide if they are downloading the right images.

**Comment by EC-O-DE** [comment]
For inspiration: ext's like Image Downloader and Picture Download Professional have "gallery" features - those are far from perfect - but would be nice to see similar with this ext :)

**Comment by DelKatey** [comment]
Sorry, it was only now that I noticed that there was a "Gallery" button that did the trick.
