### ISSUE TITLE
Feature Request : Save defaults.

### ISSUE THREAD

**Issue by fedemas1969** [belaviyo/save-images#30]
I don't know if i cant found this. Every single time you need to put the options? 
Normally i need same options to download different projects that they are in different links. EG. file type: jpg, gif and minimum size: 100000b
Each different link i need to enter the options again.
Thank you

**Comment by belaviyo** [comment]
This extension has an internal method to persist your settings, though it seems like in some browsers `localStorage` is not a good place for saving settings. As of the next release, the extension switches to `chrome.storage` which is more reliable. Please reopen if you still have the issue after the next release.
