### ISSUE TITLE
Website doesn't work

### ISSUE THREAD

**Issue by pr0advocate** [belaviyo/save-images#38]
This website doesn't work. (Does pull only the image selected but not the other in the list reardless of depth selected)
[pr0gramm.com/top](pr0gramm.com/top)

Images are linked on the website as follows:
```
<a class="silent thumb" id="item-3832881" href="/top/3832881">
    <img src="//thumb.pr0gramm.com/2020/04/12/edf5d30116561066.jpg">
</a>
```
img src however just leads to the thumbnail. [pr0gramm.com/top/3832881](pr0gramm.com/top/3832881) would lead to the image. However the tool doesn't search this link I guess

**Comment by belaviyo** [comment]
The destination page uses a JavaScript code to load the image. There is no track of the image URL in the `"/top/3832881"` page. So the extension cannot extract the link.

**Comment by pr0advocate** [comment]
The image link would be [https://img.pr0gramm.com/2020/04/12/473453d9373f9dab.jpg](https://img.pr0gramm.com/2020/04/12/473453d9373f9dab.jpg)

And is listed in the HTML page of "/top/3832881"
`<img class="item-image-actual" src="//img.pr0gramm.com/2020/04/12/473453d9373f9dab.jpg" style="width: 392px; height: 507px;">`

**Comment by belaviyo** [comment]
You need to see the actual page source, not the rendered one;
view-source:https://pr0gramm.com/top/3832881

As you can see the page is very small and uses JS for building the img element.

**Comment by pr0advocate** [comment]
Any chance that any future version can handle such JS loads?

**Comment by belaviyo** [comment]
Unfortunately not. There is no secure way to build documents.
