### ISSUE TITLE
Can't Save Multiple Images With Same Name

### ISSUE THREAD

**Issue by CaseyStellar** [belaviyo/save-images#39]
Hello, I've found across a few sites that have multiple images with the same name, let's say "image.jpg", that Download All Images isn't able to save; it just saves one at random. I don't see any setting that allows multiple images with same name to be downloaded. Am I missing something or is this not a feature?

**Comment by belaviyo** [comment]
We used to have a method to auto-increment similar filenames, but at some point, it is stripped away! Should be fixed by the next release. Thanks for the report.

**Comment by CaseyStellar** [comment]
Alright, thank you.
