### ISSUE TITLE
Incorrect Date on downloads

### ISSUE THREAD

**Issue by genartpb** [belaviyo/save-images#40]
When I download an image an incorrect date is added.  I seems to be my current system date & time minus 9 hours.  I'm currently in Australia and am usually in the UK which is 9 hours behind us at present so this may be a possible cause.

Mac OS X 10.14.6 - Firefox 75.0 - Download All Images current version

**Comment by belaviyo** [comment]
The extension uses the JavaScript "Date()" function of your browser to determine the current time. Do you get the correct time in the browser console? (right-click on a page -> inspect -> Console tab -> type "Date()" and press Enter)

**Comment by genartpb** [comment]
When I do this procedure I get the correct date and time.  When I download using 'Download All Images' the images are tagged with the previous day's date.

**Comment by genartpb** [comment]
OK - a bit more checking.  When I download an image the zip file has the CORRECT date and time however the image itself is tagged precisely 10 hours earlier.

**Comment by belaviyo** [comment]
I see, it is related to https://github.com/Stuk/jszip/issues/369

It is fixed now. Thanks for the report.
