### ISSUE TITLE
The underbar of the file name is changed to hyphen and saved

### ISSUE THREAD

**Issue by hfkais** [belaviyo/save-images#41]
Hello, I am using your extension usefully. Thank you very much. 
I used the save-images extension today and found one strange thing. 
If there is an underbar in the image file name, it is saved as hyphen when it is saved.
for example, A file called **20200424083328060_1.jpg** is displayed on the webpage. If you download it using the save-images extension, it will be saved as **20200424083328060-1.jpg**. 
I've looked for options or GitHub to solve this, but I haven't found a way. So I post an issue like this. Can you help me? Thank you.

**Comment by belaviyo** [comment]
Thanks for the report. Should get fixed by the next release.
