### ISSUE TITLE
Copy lots of image links [Android]

### ISSUE THREAD

**Issue by Brian1ee7** [belaviyo/save-images#43]
Hello Devs,

I've tried copying 8,000+ image links at the Gallery but it doesn't copy.

I've tested using Firefox and Yandex Android Version.

Around 5,000 image links seems can be copied. It would be good if there's an option where you can set a range then you can change its "selected" state so we can copy image links part by part and doesn't not need to worry about mobile capabilities regarding copying image links.

I have a question regarding "Stop" button when loading image links. Can we use the "Stop" button but the already loaded images can still be accessed in the Gallery?

Thank you very much.

Sincerely,
Brian

**Comment by belaviyo** [comment]
I added a new check to download links in a text format if copying failed. Haven't tested it though, so please reopen if it is not fixed.
