### ISSUE TITLE
How could one download the images without zipping / packaging them?

### ISSUE THREAD

**Issue by Cletos** [belaviyo/save-images#51]
How could one download the images without zipping / packaging them?

**Comment by rogue-script** [comment]
Here's a workaround.  Check the box "save dialog".  Then after it downloads the images but before it makes the ZIP file you get a dialog, where the ZIP file should go.  Ignore it for now.  Elsewhere, copy the folder of files to where you want them.  They have different mtimes, and you can see that they're different with `ls -lt --full-time`.  Then once you have the images elsewhere, do whatever you want with the dialog.  I recommend cancelling it.

**Comment by belaviyo** [comment]
We now have "Save Dir" option which directly writes to the disk. So I am closing this.
