### ISSUE TITLE
When the <img> tag is nested under the <a> tag, even if the level is set to 3, the original image cannot be downloaded.

### ISSUE THREAD

**Issue by dujianchi** [belaviyo/save-images#56]
the source code of website like:
```
<a href="preview_html">
    <img src="thumbnail"/>
</a>
```  
![screenshot_20210430203536](https://user-images.githubusercontent.com/7309424/116696467-89909380-a9f4-11eb-9acd-b89e85a73c2c.png)
![screenshot_20210430204434](https://user-images.githubusercontent.com/7309424/116696791-f146de80-a9f4-11eb-9f18-c3ada27e3a40.png)

https://image.baidu.com/search/index?z=&tn=baiduimage&word=view&pn=0&ie=utf-8&oe=utf-8&fr=&se=&sme=&width=1920&height=1080

**Comment by ray-lothian** [comment]
I added an example to the test page based on your report and the extension can grab the original image only when the deep search is set to level 2. However, I was not able to debug the provided page. This page is very slow on my network so running level two is pretty much not doable!

What is your browser?

**Comment by dujianchi** [comment]
> 
> 
> I added an example to the test page based on your report and the extension can grab the original image only when the deep search is set to level 2. However, I was not able to debug the provided page. This page is very slow on my network so running level two is pretty much not doable!
> 
> What is your browser?
  
_My English is not very good. If there is any inappropriate expression, please forgive me._  
  
The browser I use is "Firefox 88.0 (64 bit)". According to what you say I tried again, set to level 2 and just check "save if unknown", it really works, but the downloaded file contains some button pictures or web icons. Does not particularly affect the use. The site opens slowly, probably because it mainly provides service for my country.

**Comment by dujianchi** [comment]
It may just be me improper use, rather than issue. Thank you for everything.
