### ISSUE TITLE
Feature request: aspect ratio filter

### ISSUE THREAD

**Issue by Brian1ee7** [belaviyo/save-images#57]
Please add an option where we can select an aspect ratio to filter images, for example, 16:9, then we can check a box, for example:
width >= aspect ratio of image height,
width <= aspect ratio of image height,
height >= aspect ratio of image width, or
height  <= aspect ratio of image width

together with dimension pixels filter, I want to filter images with min. height of 1080 and width must be >= aspect ratio of the image height.

**Comment by jssr67** [comment]
If we have an "aspect ratio range" filter, a selectable option to seach for the "inverse AR range" as well would help - the filter, when the option is selected, would then become orientation independent.
