### ISSUE TITLE
Not working on mangakakalot anymore

### ISSUE THREAD

**Issue by M3gue** [belaviyo/save-images#61]
Hi, thanks for all the work

I'm having trouble downloading the images from mangakakalot. In version 0.7.7 it worked fine, but now in 0.9 it does not work

For example in: https://mangakakalot.com/chapter/qk919632/chapter_24, in version 0.9 when I try to download the images it does not show a preview or the weight of the images:

![0 9](https://user-images.githubusercontent.com/90344568/132555174-b0441058-9b32-42f3-a38b-c7a03011f75c.jpg)

And when I download the file only weighs 2,78 KB and them it shows this, even when I verified that the format is correct:

![err](https://user-images.githubusercontent.com/90344568/132556211-07ed9221-156f-4b7f-8656-42c428d7bb63.jpg)

On this same page in version 0.7.7 it does work. Although it does not show the preview, it shows the weight and the downloaded images can be opened:

![0 7](https://user-images.githubusercontent.com/90344568/132556557-4b3052da-54ed-44af-a4b9-aa9cc2f419a4.jpg)

The same problem is repeated on other pages like this: https://klmanga.com/read-renai-harem-game-shuuryou-no-oshirase-ga-kuru-koro-ni-raw-chapter-17.html

**Comment by belaviyo** [comment]
thanks for the report. It is fixed on 0.9.4 release.
