### ISSUE TITLE
Zip not saving

### ISSUE THREAD

**Issue by knottshawk** [belaviyo/save-images#64]
I see the dialogue, and there are images in the "gallery" section, but when I tell it to 'save' the directory in my downloads folder is empty and remains empty. It doesn't appear to actually be saving the zip file anywhere. 

This is on Mac OS with Chrome Version 96.0.4664.110 (Official Build) (x86_64)

**Comment by belaviyo** [comment]
Can you try the extension on a clean profile? This extension uses manifest V3, and you might have an extension that conflicts.

https://support.google.com/a/users/answer/9310144?hl=en#2.2
