### ISSUE TITLE
Feature Request: Display "Finished" dialogue when saving is complete

### ISSUE THREAD

**Issue by saabfactory** [belaviyo/save-images#65]
When I use the extension on a number of tabs and have them all downloading, I lose track of which tabs have been processed and completed, and which ones I've yet to do.

It would be great to have a dialogue or some other indication that the save is complete so I can come back to the tab later and close it if done.

**Comment by belaviyo** [comment]
<img width="58" alt="Screenshot 2022-01-18 at 02 13 22" src="https://user-images.githubusercontent.com/1221138/149888930-6c9a9d09-ad33-4479-a81e-0565fa8d62e2.png">

There is going to be a "✓" badge for successful jobs.

**Comment by saabfactory** [comment]
That's tremendous, thanks so much!
