### ISSUE TITLE
Feature: Add [url] to "Save in" Template (like [title], [date], [time])

### ISSUE THREAD

**Issue by JustaNormalGuy230** [belaviyo/save-images#66]
[url] would have to filter/substitute characters like slashes (colons).  In my particular case, I'm only after a long number at the end of the URL, but I can imagine someone wanting to preserve the original URL as much as possible.  Substituting "_" for "/" is a common practice (not sure what a good substitute for ":" would be) ... 

I'll take a look if I might be able to code it in myself, but I don't think it would be that difficult.  Maybe the [url] keyword already exists?  Thanks!

Nice Discussion on File Name Sanitation of URLs:
 https://stackoverflow.com/questions/2668854/sanitizing-strings-to-make-them-url-and-filename-safe

**Comment by belaviyo** [comment]
new keywords `[href]`, `href-hostname]`, `[href-pathname]`, `[href-search]`, and `[href-hash]`

**Comment by belaviyo** [comment]
btw, if you use the "Save Dir" option, it will create a meta file in the directory for you with the full URL included.

**Comment by JustaNormalGuy230** [comment]
Thanks for the quick add and the info!  [href-pathname] is working fine for me.  For the moment....

.... I've been playing around with this particular extension that Auto BookMarks URL domain pages:
https://github.com/txusko/AutoBookmarks

Unfortunately it's 6 years old and a lot of the code is broken (fails to fetch the Web Page Title properly, doesn't allow one to navigate/save the bookmark in an existing deep subfolder path and saves all bookmarks from all of the URL Domain and not a specific subdirectory path of the domain only).  The Good News is that it successfully Auto Bookmarks, so that part of the code is solid! I have not tried to contact the author yet, for any guidance/advice....

FYI: Another useful Chrome Extension besides this one, is "Save Text to File", where I have opened this Issue, but there is a work-around for the moment:
https://github.com/bobbyrne01/save-text-to-file-chrome/issues/8

The work-around involves never enabling the Host Application; seems the latest python versions are breaking the proper saving of particular UniCode characters, like there is a default setting directive, needed.  I'm mentioning this extension because it compliments your work saving images, as this extension saves UniCode Text by marking, then right clicking in the context menu.
