### ISSUE TITLE
images saved as an unopenable "File"

### ISSUE THREAD

**Issue by realtoraveryjones** [belaviyo/save-images#8]
2 issues in Firefox 59.0 64 bit Download All Images add on: First, I click save images and use the "open save dialog" option bottom right to save the folder, then after I click save it saves all of the pictures as a file with the extension "File". There isn't a program to open it or read it. Once in a while it saves the files as a zipped folder, but not often. Second, I can only download images from one tab at a time or else it resaves the same images into a duplicate folder with the same name. For example, I download bing images  for Australia in one tab. In another tab I save images for New Zealand. When I do this back to back by changing window tabs, it doesn't save the second group of images that I selected. Rather than saving Australia's images in Australia's folder, and New Zealand's images in New Zealand's folder, it saves to folders with Australia's images. What can be done to remedy these issues? Thank you.

**Comment by belaviyo** [comment]
>  it saves all of the pictures as a file with the extension "File".

Can you provide the instruction how to regenerate this?

> Second, I can only download images from one tab at a time

This is fixed on the latest release. Thanks for the report.
