### ISSUE TITLE
Does not find all images on app.adventuresinodyssey.com

### ISSUE THREAD

**Issue by frederickjh** [belaviyo/save-images#80]
With the default settings the extension only finds one image at the following address: [https://app.adventuresinodyssey.com/albums](https://app.adventuresinodyssey.com/albums). There are clearly more images on this webpage but only one shows up in the gallery.

**Comment by belaviyo** [comment]
Thanks for the report.

This website uses the Flutter engine. Currently, it uses custom elements to add content. The recent commit addresses this issue (the extension now inspects the body of custom elements). Note that the latest Flutter version includes a custom rendering engine that loads the entire DOM onto a single canvas element. Therefore, if the website owner upgrades the engine, the extension may not be able to capture images once again.

**Comment by frederickjh** [comment]
How long will it be before the new version is available in the browser? Just checked for updates none available current version in my Firefox is 0.7.9 is from March 8, 2023.

**Comment by belaviyo** [comment]
It is still on review. Usually it takes about 3 days for AMO to accept a new version.
