### ISSUE TITLE
saved filenames are truncated from beginning

### ISSUE THREAD

**Issue by rdodger** [belaviyo/save-images#9]
Frequently when retrieving at level 2 I see saved files with the beginning of the file name truncated, such as "rol_Brown_772734.jpg" where the actual filename was "Carol_Brown" etcetera.  This behavior does not seem associated with any constant number of characters in the filename.  Can this be replicated, analyzed and corrected?

**Comment by morues** [comment]
Yes, there is a limit of 20 chars for each filename. We needed it before using the ZIP archiving method. In the latest release, I allow 30 chars for filenames. If it is still causing issues please provide a sample page.

**Comment by belaviyo** [comment]
Yes, there is a limit of 20 chars for each filename. We needed it before using the ZIP archiving method. In the latest release, I allow 30 chars for filenames. If it is still causing issues please provide a sample page.
