### ISSUE TITLE
Bug : Rename zip file does not work anymore on Chrome

### ISSUE THREAD

**Issue by saint-seiya115** [belaviyo/save-images#98]
Hi! 

First thank you for you addon, it's so good ! 

Then, since yesterday, it seems that I have a problem with automatic rename of zip file created with Chrome.
As you see in the screen below, I kept the default name for zip filename.
<img width="530" alt="image" src="https://github.com/user-attachments/assets/d1fcc292-c25a-4176-a13d-0c33f6171386">
But when I try to save the file in Chrome, it uses some UUID instead of the filename shown in the popup.
<img width="605" alt="image" src="https://github.com/user-attachments/assets/204b33eb-145c-43b3-b20d-ed1ce29a1fe2">
Even if "save dialog" is not ticked, an UUID is used instead.

My actual version of Chrome : 127.0.6533.120

I don't have this problem with Firefox.

**Comment by belaviyo** [comment]
You most likely have an extension that intercept downloads. Try on a clean profile to confirm;

https://support.google.com/chrome/answer/2364824?hl=en&co=GENIE.Platform%3DDesktop
